### ISSUE TITLE
Failed to load the remote-edit package (deserializer issue?)

### ISSUE THREAD

**Issue by gmemstr** [sveale/remote-edit#138]
Atom isn't letting me automatically create a proper bug report, so here's my manual one:

Stack Trace:
```
TypeError: TextEditor.registerDeserializer is not a function
    at C:\Users\Gabriel\.atom\packages\remote-edit\lib\model\remote-edit-editor.coffee:26:16
    at Object.<anonymous> (C:\Users\Gabriel\.atom\packages\remote-edit\lib\model\remote-edit-editor.coffee:23:5)
    at Object.<anonymous> (C:\Users\Gabriel\.atom\packages\remote-edit\lib\model\remote-edit-editor.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\Gabriel\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Gabriel\.atom\packages\remote-edit\lib\main.coffee:2:20)

```

Steps to reproduce: 

I just opened Atom, and I'd used it earlier in the day. Not sure if Atom updated without me noticing or something else.

Atom version: `1.1.0`

Other packages: 

I disabled/removed all the other community packages I don't need. 

Other notes: 

None.

**Comment by longhuei** [comment]
I'm seeing this error only after updating to 1.1.0. Package no longer works! Help needed!!

**Comment by howanghk** [comment]
This happen to me on Mac too.

**Comment by jasonevrtt** [comment]
I'm also getting the same error now, but I'm also getting this inside of the 'Updates' page in Atom...

```
Cannot find module 'C:\Users\ge02dg\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\emissary'
```

Here's all the info from the error report...

**Atom Version**: 1.1.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package, v1.8.21


### Stack Trace

Failed to load the remote-edit package

```
At TextEditor.registerDeserializer is not a function

TypeError: TextEditor.registerDeserializer is not a function
    at C:\Users\ge02dg\.atom\packages\remote-edit\lib\model\remote-edit-editor.coffee:43:16
    at Object.<anonymous> (C:\Users\ge02dg\.atom\packages\remote-edit\lib\model\remote-edit-editor.coffee:253:5)
    at Object.<anonymous> (C:\Users\ge02dg\.atom\packages\remote-edit\lib\model\remote-edit-editor.coffee:255:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\ge02dg\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\ge02dg\.atom\packages\remote-edit\lib\main.coffee:2:20)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "cold-ui",
      "cold-syntax"
    ]
  },
  "remote-edit": {}
}
```

### Installed Packages

```coffee
# User
cold-syntax, v1.3.0
cold-ui, v1.4.0
color-picker, v2.0.12
pretty-json, v0.4.1
remote-atom, v1.2.7
remote-edit, v1.8.21

# Dev
No dev packages
```




```

**Comment by ilaudy** [comment]
same problem after I updated to Atom Version: 1.1.0

**Comment by dorian-marchal** [comment]
Same error after upgrading to 1.1.0

**Comment by markusdanek** [comment]
+1

OSX 10.11 - Atom 1.1.0

**Comment by matthewknecht** [comment]
You should be able to fix this by manually reverting to the previous version, I'm currently testing to see if this is plausible

**Comment by karita-dev** [comment]
+1 :/
OSX 10.11 - Atom 1.1.0

**Comment by beardedeagle** [comment]
Same for OSX

**Comment by flamedmg** [comment]
windows 10 / same problem

**Comment by matthewknecht** [comment]
@sveale I'm assuming this is a package conflict with the recent Atom update? I would just suggest to people to install the previous version if they have this issue. 
(Link to Atom version which works: https://github.com/atom/atom/releases/tag/v1.0.19 )

**Comment by Spartibartfast** [comment]
+1 Ubuntu 64bit Atom 1.1.0

**Comment by gmemstr** [comment]
This is obviously a very serious issue in 1.1.0. Hope it gets fixed soon because most of my workflow relies on it. :+1:

**Comment by Elyorito** [comment]
OSX 10.11.1 - Atom 1.1.0... 
:-(

**Comment by designarti** [comment]
+1 Windows 8.1
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package, v1.8.21


### Stack Trace

Failed to load the remote-edit package

```
At TextEditor.registerDeserializer is not a function

TypeError: TextEditor.registerDeserializer is not a function
    at C:\Users\designarti\.atom\packages\remote-edit\lib\model\remote-edit-editor.coffee:26:16
    at Object.<anonymous> (C:\Users\designarti\.atom\packages\remote-edit\lib\model\remote-edit-editor.coffee:23:5)
    at Object.<anonymous> (C:\Users\designarti\.atom\packages\remote-edit\lib\model\remote-edit-editor.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\designarti\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\designarti\.atom\packages\remote-edit\lib\main.coffee:2:20)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.19.0
remote-edit, v1.8.21

# Dev
No dev packages
```

**Comment by sveale** [comment]
Looks like this issue started because of a change in how ``TextEditor`` in atom handles serializing, see https://github.com/atom/atom/commit/04bda33c102c64ecd36c6cbc146bc5f8450122a1.

Should be resolved in commit d9d27c53a08b274b24eacfa32ae3801e62c8e6e, released in remote-edit@v1.8.22.

**Comment by sveale** [comment]
I'd really appreciate it if any of y'all could try out the fix and let me know if it resolves the issue.

**Comment by gmemstr** [comment]
@sveale Can confirm the update has fixed it. Thank you so much :+1:

**Comment by MarcinWieczorek** [comment]
Just got same error trying to use Atom.

**Comment by dorian-marchal** [comment]
Thanks, @sveale :+1:

**Comment by MarcinWieczorek** [comment]
Fixed after update ;)
Thanks!

**Comment by designarti** [comment]
Thanks!

**Comment by manoloviejo** [comment]
Thank you very much  @sveale!! Fixed.

**Comment by markacola** [comment]
Thanks for the speedy fix @sveale ! You're awesome!

**Comment by xd1936** [comment]
Thanks!

**Comment by ghoben** [comment]
[Enter steps to reproduce below:]

1. starting up atom

**Atom Version**: 1.2.4
**System**: #######
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package, v1.8.21


### Stack Trace

Failed to load the remote-edit package

```
At TextEditor.registerDeserializer is not a function

TypeError: TextEditor.registerDeserializer is not a function
    at C:\Users\GG\.atom\packages\remote-edit\lib\model\remote-edit-editor.coffee:26:16
    at Object.<anonymous> (C:\Users\GG\.atom\packages\remote-edit\lib\model\remote-edit-editor.coffee:23:5)
    at Object.<anonymous> (C:\Users\GG\.atom\packages\remote-edit\lib\model\remote-edit-editor.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\GG\AppData\Local\atom\app-1.2.4\resources\app.asar\src\compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\GG\.atom\packages\remote-edit\lib\main.coffee:2:20)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "remote-edit": {}
}
```

### Installed Packages

```coffee
# User
auto-detect-indentation, v0.4.2
auto-indent, v0.5.0
color-picker, v2.0.13
indent-guide-improved, v1.4.5
linter, v1.11.3
mocha, v0.0.7
node-debugger, vundefined
node-resolver, v1.0.1
remote-atom, v1.3.6
remote-edit, v1.8.21
Remote-FTP, v0.7.14

# Dev
No dev packages
```

**Comment by ghoben** [comment]
I cannot update to 1.8.23, which will fix this issue. I'm always getting:

Updating to “remote-edit@1.8.23” failed.Hide output…

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, open 'C:\Users\GG\.atom\packages\remote-edit\node_modules\atom-space-pen-views\node_modules\space-pen\node_modules\jquery\src\serialize.js'

**Comment by fractalf** [comment]
This happened to me just now on a fresh install..

**Atom Version**: 1.9.0-beta0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package, v1.8.24

### Stack Trace

Failed to load the remote-edit package

```
At Cannot find module 'C:\Users\MediehusetTek\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\display-buffer'

Error: Cannot find module 'C:\Users\MediehusetTek\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\display-buffer'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (C:\Users\MediehusetTek\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (C:\Users\MediehusetTek\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/MediehusetTek/.atom/packages/remote-edit/lib/model/remote-edit-editor.coffee:9:17)
    at Object.<anonymous> (file:///C:/Users/MediehusetTek/.atom/packages/remote-edit/lib/model/remote-edit-editor.coffee:1:1)
    at Module._compile (C:\Users\MediehusetTek\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\MediehusetTek\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\MediehusetTek\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/MediehusetTek/.atom/packages/remote-edit/lib/main.coffee:3:20)
    at Object.<anonymous> (file:///C:/Users/MediehusetTek/.atom/packages/remote-edit/lib/main.coffee:1:1)
    at Module._compile (C:\Users\MediehusetTek\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\MediehusetTek\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\MediehusetTek\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\MediehusetTek\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\package.js:715:27)
    at C:\Users\MediehusetTek\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (C:\Users\MediehusetTek\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\MediehusetTek\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\MediehusetTek\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\package-manager.js:457:14)
    at C:\Users\MediehusetTek\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\package-manager.js:402:19
    at Config.module.exports.Config.transact (C:\Users\MediehusetTek\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\MediehusetTek\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\package-manager.js:397:19)
    at C:\Users\MediehusetTek\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\atom-environment.js:749:28
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
remote-edit, v1.8.24 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.0 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.0 (inactive)
bookmarks, v0.41.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.38.1 (inactive)
fuzzy-finder, v1.2.0 (inactive)
git-diff, v1.0.1 (inactive)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (inactive)
image-view, v0.58.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v0.53.1 (inactive)
notifications, v0.64.1 (inactive)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.67.1 (inactive)
status-bar, v1.3.1 (inactive)
styleguide, v0.46.0 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (inactive)
timecop, v0.33.1 (inactive)
tree-view, v0.208.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.34.0 (inactive)
whitespace, v0.32.2 (inactive)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.0 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.36.2 (inactive)
language-gfm, v0.86.0 (inactive)
language-git, v0.13.0 (inactive)
language-go, v0.42.0 (inactive)
language-html, v0.44.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.22.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.0 (inactive)
language-less, v0.29.3 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.0 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.68.5 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.52.0 (inactive)
language-shellscript, v0.22.3 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.21.1 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.8 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by thorstenhirsch** [comment]
I've got the same problem as fractalf with the same version/platform/packages.

**Comment by denisdl** [comment]
Ubuntu 14.04, Atom 1.9.0, Remote Edit 1.8.24
Error happened after update Atom 1.8.0 to 1.9.0

Cannot find module '/usr/share/atom/resources/app.asar/src/display-buffer'

Error: Cannot find module '/usr/share/atom/resources/app.asar/src/display-buffer'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/denis/.atom/packages/remote-edit/lib/model/remote-edit-editor.coffee:9:17)
    at Object.<anonymous> (/home/denis/.atom/packages/remote-edit/lib/model/remote-edit-editor.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/denis/.atom/packages/remote-edit/lib/main.coffee:3:20)
    at Object.<anonymous> (/home/denis/.atom/packages/remote-edit/lib/main.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:715:27)
    at /usr/share/atom/resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:457:14)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:402:19
    at Config.module.exports.Config.transact (/usr/share/atom/resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app.asar/src/package-manager.js:397:19)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:749:28

**Comment by dmase44** [comment]
Win 7 beta 1.9.0 But now using stable 1.8.0
I'm having the same issue. I have been using the atom beta versions. It worked great til beta 1.9.0. which will not load remote-edit. I installed the stable 1.8.0 over it & it worked fine til I shut atom down. On restart I get the same error message as before:
Cannot find module 'C:\Users\Gonzo\AppData\Local\atom\app-1.9.0\resources\app.asar\src\display-buffer'. The Stack Trace is similar to fractalf above. 
I removed every instance of atom I could find. Reinstalled stable 1.8.0 & same issue til I reinstall 1.8.0 over it & it works fine til I shut it down. The error states: The error was thrown from the remote-edit package. This issue has already been reported! It appears it hasn't been resolved as it's been this way for quite awhile. Any ideas?

**Comment by h4km** [comment]
![issu](https://cloud.githubusercontent.com/assets/18589069/17316164/e007fae6-589b-11e6-8e69-61051da15fa4.jpg)
me too

**Comment by Liaorio** [comment]
The same problem: Cannot find module '/usr/share/atom/resources/app.asar/src/display-buffer'.
But how to roll back to old version (mac os)?

**Comment by bontiv** [comment]
Same in version 1.9.1.

Cannot find module 'C:\Users\bonnet\AppData\Local\atom\app-1.9.1\resources\app.asar\src\display-buffer'

**Comment by Nollikino** [comment]
@Liaorio @bontiv @denisdl @fractalf  Your issues is because "display-buffer" has been deprecated since v1.9.x.

There is a pull request that resolves this issue currently. You can find it at #187. If you don't want to wait for the merge, then you can always check out the changes to the code in the previously mentioned pull request and manually change the code.
